name: Golang Build

on:
  push:
    branches: "*"

env:
  DOCKER_REPOSITORY: tourna
  DOCKER_IMAGE: aelm-workshop-23
  GOLANG_VERSION: 1.21.x

jobs:
  build:
    runs-on: ubuntu-latest
    # Code Build steps
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Build
        run: go build -o ../bin/workshop -v ./...
        working-directory: workshop-service
      - name: Upload /bin folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workshop
          path: bin/
          retention-days: 1